# Homework w06d02 - SQL joins

#### 1. Connect to the Northwind database

In [1]:
%load_ext sql

In [2]:
%%sql postgresql://dsi_student:gastudents@dsi.c20gkj5cvu3l.us-east-1.rds.amazonaws.com/northwind

SELECT * FROM information_schema.tables WHERE table_schema = 'public';

20 rows affected.

[(u'northwind', u'public', u'categories', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'customercustomerdemo', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'customerdemographics', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'customers', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'employees', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'employeeterritories', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'order_details', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'orders', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'products', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'region', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'shippers', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'shippers_tmp', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'suppliers', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'territories', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'usstates', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'table1', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'movies', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'ratings', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'categoriesmerged', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None),
 (u'northwind', u'public', u'region2', u'BASE TABLE', None, None, None, None, None, u'YES', u'NO', None)]

#### 2. Use joins between the tables of employeeterritories, territories, regions,  orders, order_details and products to produce a table containing the columns EmployeeID, RegionDescription, TerritoryDescription, OrderID, ProductID and UnitPrice.

#### Hint: Create a copy of the region table and insert a new column into this copy which translates Eastern to east, Western to west, etc.

#### 3. What is the total price of units sold by the individual employees?

#### 4. What is the total price of units sold per RegionDescription (Eastern, Western, etc.)?

#### 5. What is the total price of units sold per TerritoryDescription (Boston, Denver, etc.)?